64kramsystem/schedule_manager

- .gitignore
- Gemfile
> Add project support files

- replan
- replan.lib/replan_codec.rb
- replan.lib/replanner.rb
- spec/replan/replan.lib/replan_codec_spec.rb
This is in preparation to the noarchive mode.
> Move all the skip replans also in regular mode

- replan
This allows unit testing also of the orchestration logic.
> Refactoring: Create launcher class (Replan)

- replan.lib/reworker.rb
- spec/replan/replan.lib/reworker_spec.rb
Also added Reworker test suite.
> Reworker: Add HH:MM -H.MMh format (and reverse)

- replan.lib/readder.rb
- replan.lib/replan_helper.rb
- replan.lib/replanner.rb
- replan.lib/shared_constants.rb
- spec/replan/replan.lib/replan_helper_spec.rb
- spec/replan/replan.lib/replanner_spec.rb
Also done some minor refactorings.
> Add time section separators when adding a new date section

- replan
- replan.lib/readder.rb
- replan.lib/replan_helper.rb
- replan.lib/retemplater.rb
- replan.lib/shared_constants.rb
- spec/replan/replan.lib/retemplater_spec.rb
Add the option to use a template, whose content is integrated in the next day.
> Add templating logic

- replan
Currently, just prints the stack trace when there is an error.
> Add debug mode

- replan.lib/adjusted_date_wday.rb
- replan.lib/relister.rb
- replan.lib/replan_codec.rb
- replan.lib/replan_helper.rb
- spec/replan/replan.lib/relister_spec.rb
- spec/replan/replan.lib/replan_codec_spec.rb
- spec/replan/replan.lib/replan_helper_spec.rb
Also made some (mostly supporting) changes.
> Relister: Allow empty dates (sections) and non-replan events

- replan.lib/relister.rb
- spec/replan/replan.lib/relister_spec.rb
> Fix Relister events selection - was missing non-replan events

- Gemfile
- replan.lib/replan_codec.rb
- replan.lib/replan_lexer.rb
- replan.lib/replan_parser.rb
- replan.lib/replanner.rb
- replan_parser/build.sh
- replan_parser/lexer.rex
- replan_parser/parser.y
- spec/replan/replan.lib/replan_codec_spec.rb
- spec/replan/replan.lib/replanner_spec.rb
Also removed useless code from the lexer, and Timecop gem to the test group.
> Add weekday support to "next" replan field

- replan.lib/retemplater.rb
- spec/replan/replan.lib/retemplater_spec.rb
Also made minor cosmetic cleanups.
> Retemplater: Automatically fill missing brackets

- replan.lib/replan_codec.rb
- replan.lib/replan_lexer.rb
- replan.lib/replan_parser.rb
- replan.lib/replanner.rb
- replan_parser/build.sh
- replan_parser/lexer.rex
- replan_parser/parser.y
- spec/replan/replan.lib/replan_codec_spec.rb
Allow updating a whole line, for irregular events, which frequently need replan parameter changes.
> Add update whole line

- replan.lib/replan_codec.rb
- replan.lib/replanner.rb
- spec/replan/replan.lib/replan_codec_spec.rb
- spec/replan/replan.lib/replanner_spec.rb
This is very helpful for recurring but irregular events.
> Replanner: On full update, consider recurring the events with weekday but no interval

- replan.lib/replan_codec.rb
- replan.lib/replanner.rb
- spec/replan/replan.lib/replan_codec_spec.rb
- spec/replan/replan.lib/replanner_spec.rb
Large refactornigs, started from adding the `sU` replan support (not in this PR).
> Large refactorings

- replan.lib/replanner.rb
- spec/replan/replan.lib/replanner_spec.rb
Fix an old bug, and two introduced with the last PR. Also made a minor simplification.
> Fix a few bugs

- replan.lib/reworker.rb
- spec/replan/replan.lib/reworker_spec.rb
Example:
- work (something) -1.5h
> Add work task comment option

- replan
- replan.lib/reworker.rb
- spec/replan/replan.lib/reworker_spec.rb
Compute the hours of work for the current day.
> Add work hours count functionality

- replan.lib/replanner.rb
- spec/replan/replan.lib/replanner_spec.rb
Currently, only `curdate` is implemented.
> Add interpolations: tokens that apply functions to the line

- replan.lib/replan_lexer.rb
- replan.lib/replanner.rb
- replan_parser/build.sh
- replan_parser/lexer.rex
- spec/replan/replan.lib/replanner_spec.rb
Very convenient in certain cases.
> Replanner: Add support for `day+` (day plus one week)

- replan.lib/replan_helper.rb
- replan.lib/retemplater.rb
- spec/replan/replan.lib/retemplater_spec.rb
This was handled, but not very nicely, which made the logic a bit confusing; now it's very clean, which also allows unifying the current logic as described in the comment.
> Improve handling of user's unexpected spaces (and similar cases)

- replan.lib/replanner.rb
- spec/replan/replan.lib/replanner_spec.rb
Also, improved some UT titles in the related test suite.
> Fix: On fixed timestamp, the time was not copied to the new line

- replan
- replan.lib/relister.rb
- spec/replan/replan.lib/relister_spec.rb
Also renamed JSON mode to export mode, and separated it from the former.
> Export: Add "event" event type

- replan.lib/replanner.rb
- spec/replan/replan.lib/replanner_spec.rb
The user may want to change the date.
> On full update, prompt for update even if skipping is specified

- .github/workflows/ci.yml
- Gemfile
- spec/replan/replan.lib/replanner_spec.rb
- Add rexical to Gemfile
- replanner_spec: Remove date parsing stubbing
> Minor cleanups

- replan.lib/relister.rb
- spec/replan/replan.lib/relister_spec.rb
- multiple notes on the same line were not removed
- the wildcard was greedy
> Relister: Fix notes removal

- replan.lib/replan_codec.rb
- replan.lib/replan_lexer.rb
- replan.lib/replan_parser.rb
- replan.lib/replanner.rb
- replan_parser/build.sh
- replan_parser/lexer.rex
- replan_parser/parser.y
- spec/replan/replan.lib/replan_codec_spec.rb
- spec/replan/replan.lib/replanner_spec.rb
Schedules an event in the future, without repetition (replanning)
> Implement "once" functionality

- replan.lib/replanner.rb
- spec/replan/replan.lib/replanner_spec.rb
> Improve error message for multiple instances update error

- replan
- replan.lib/replanner.rb
- spec/replan/replan.lib/replanner_spec.rb
Very convenient, when cleaning up.
> Implement "skips only", as replacement of "no move"
